FROM node:20-alpine AS build

WORKDIR /app

COPY frontend/package*.json frontend/pnpm-lock.yaml* ./
COPY frontend/ ./

# Install dependencies and build
RUN npm install
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
